

export const ACTIONTYPES = {


    /**
     * GET Movie ACTION TYPES
     */

    MOVIE_FETCH_START:"MOVIE_FETCH_START",
    MOVIE_FETCH_SUCCESS:"MOVIE_FETCH_SUCCESS",
    MOVIE_FETCH_FAILURE:"MOVIE_FETCH_FAILURE",


    /**
     * Add Movie ACTION TYPES
     */

    MOVIE_CREATE_START:"MOVIE_CREATE_START",
    MOVIE_CREATE_SUCCESS:"MOVIE_CREATE_SUCCESS",
    MOVIE_CREATE_FAILURE:"MOVIE_CREATE_FAILURE",
   
}

